[project]
name = "scilab-ai"
version = "0.1.0"
description = "Scilab-AI Service - Graph RAG API"


[tool.taskipy.tasks]
run = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
dev = "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
